### ISSUE TITLE
Export JSON schema for model specification

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/python-bioimage-io#27]

**Comment by oeway** [comment]
Is this already done?


I just check the schema, and noticed there are wired keys appeared in the root: `optional_kwargs` `required_kwargs`, why is that? @FynnBe 

I am thinking maybe we should write the schema manually, in that case, will you be able to read a json schema file and use it in the python package?

**Comment by FynnBe** [comment]
> Is this already done?

yes, I forgot about this issue... 

> I just check the schema, and noticed there are wired keys appeared in the root: optional_kwargs required_kwargs, why is that? @FynnBe

The `optional_kwargs` and `required_kwargs` keys are there to specify any kwargs optional/required for model instantiation, as source points to a callable... 

> I am thinking maybe we should write the schema manually, in that case, will you be able to read a json schema file and use it in the python package?

we use marshmallow to specify the schema, which allows for more validation and exporting of the json schema (with a subset of the 'rules'). As marshmallow is more powerful, I would like to keep it this way. 

What would you want to change manually? Maybe we can just adapt the schema in marshmallow accordingly?

**Comment by oeway** [comment]
Thanks @FynnBe  for the explanation.

> The `optional_kwargs` and `required_kwargs` keys are there to specify any kwargs optional/required for model instantiation, as source points to a callable...

But this is not in our configuration specification right, is there a way to clean up the exported json schema?

> What would you want to change manually? Maybe we can just adapt the schema in marshmallow accordingly?

I would like to make a model config generator/validator plugin in javascript, so users can build model config from an UI and we can add a badge for validated model cards. Even more, for those not validated ones we show an info button where the developer can click and we can show a list of errors, warnings and suggestions.

I can either redo it in javascript and make an bioengine app for that, or we can run the marshmallow validation when we compile the yaml file to the manifest json (in a CI), then add the validation report to the generated json file.

The JSON schema is also important, even though it's a subset of the rules, we can share it between different language (e.g. Java/JS).

Related to these, I have two additional questions:
1. when I pass the yaml config to marshmallow to validate, can you generate a detailed report? Not just passed or failed, but ideally also more detailed information for different levels: error, warning, recommendation etc.

2. For the generated JSON schema, can we clean it up to remove for example keys like `required_kwargs`, it's a bit confusing when we generate an HTML form with it and it has these keys.

**Comment by FynnBe** [comment]
> But this is not in our configuration specification right, is there a way to clean up the exported json schema?

> For the generated JSON schema, can we clean it up to remove for example keys like required_kwargs, it's a bit confusing when we generate an HTML form with it and it has these keys.

sure thing, we can just drop them to have the models self-contained
Maybe we should add them to the specification, though? Let's discuss that in #31, and I'll remove them from the json schema for now.
- [ ] remove kwargs from model json schema

> I can either redo it in javascript and make an bioengine app for that, or we can run the marshmallow validation when we compile the yaml file to the manifest json (in a CI), then add the validation report to the generated json file.

Running a CI was the plan afaik... With the marshmallow schema we implemented a fast validation (format + easy to check cross field checks) and one that would require some more computation (running source code, etc..)

> when I pass the yaml config to marshmallow to validate, can you generate a detailed report? Not just passed or failed, but ideally also more detailed information for different levels: error, warning, recommendation etc.

yes, exactly which field fails why and which fields collide

**Comment by FynnBe** [comment]
- [ ] improve exported json: https://github.com/bioimage-io/bioimage-io-models/pull/22#issuecomment-650095706
