### ISSUE TITLE
Key word arguments for model specs

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/python-bioimage-io#31]
Should we add optional and required key word arguments to the model specification, as we have them for other specifications, e.g. reader, sampler, transformation?

(assumption: key word arguments have to be json serializable, no fancy stuff!)

Pros:
- consistency across specs
- most models actually do have some kwargs, like nr of channels, etc... 

Cons:
- we would have to specify model kwargs for the different weights to avoid collisions

**Comment by constantinpape** [comment]
This is outdated.
