### ISSUE TITLE
Support testing model packager

### ISSUE THREAD

**Issue by oeway** [bioimage-io/python-bioimage-io#55]
As discussed, it would be nice to support testing the model packager link.

Here is what I propose:
1. resolve the url of the following items:
   * `weights`
   * `files` key under attachments
   * `attachments` under the each weights file formats
   * `source`
   * `test_inputs` and `test_outputs`
   * `covers`
2. for each URL, we don't need to download each file during test, but send a `HEAD` request to probe the file to see if it exists.

This is the implementation in JS is here:
https://github.com/imjoy-team/bioimage-io-models/blob/94134ab9d231c219b0662862a0a0624288d7991b/src/bioimageio-packager.imjoy.html#L95-L137

**Comment by constantinpape** [comment]
@oeway I think this is outdated so I am closing this issue. If it's not outdated, I think it's best if you create a new issue in the spec repo, that now contains all the spec validation logic.
