### ISSUE TITLE
model_spec.json

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/python-bioimage-io#57]
commit c196ad70aed0dd24d679b5606b4185592d5f4db9 added an automatically generated model spec. Since it's been so long, I assume it is outdated? Also there should be some note that this file is generated - it's quite irritating. What is it's use?

**Comment by FynnBe** [comment]
@oeway was interested in a json schema version of our marshmallow schema (that is more detailed) for use in web forms... 
I'll make a PR with changing the generated file's name and add the spec version to the generated file...
