### ISSUE TITLE
Check license key to match SPDX license definition

### ISSUE THREAD

**Issue by oeway** [bioimage-io/python-bioimage-io#68]
Hi, it would be nice if we can validate that the license key is a valid SPDX identifier.

Here is a potential python package we could use to get the list: https://pypi.org/project/spdx-license-list/

@FynnBe @constantinpape

**Comment by FynnBe** [comment]
alright, looking at what this packages provides additionally, should we:
> isDeprecatedLicenseId - bool value telling you whether this license definition is oudated or not.
- warn for a deprecated licence (or fail?)?
> isFsfLibre - bool value telling you whether this license is "free software" by the definition of FSF.
> isOsiApproved - bool value telling you whether this license is "open source" by the definition of OSI.
- require it to be free/open source?? (I think we agreed on not enforcing any specific license groups, but I want to make sure I didn't just make that up...)
