### ISSUE TITLE
Enforce that the `documentation` key contains only relative path, not a URL

### ISSUE THREAD

**Issue by oeway** [bioimage-io/python-bioimage-io#70]
The current spec describe `documentation` as `Relative path to file with additional documentation in markdown.` However, the validator only check it's a URI. I noticed that some models use a generic http URL for the documentation key, which make it more complicated to render on the website. I am keen in to make it more restricted: 
 * It must be a relative path start with `./`
 * It must be a markdown file with `*.md` extension
 * URL is not allowed
 
 I added clarification to the spec docs too: https://github.com/bioimage-io/spec-bioimage-io/pull/84

**Comment by constantinpape** [comment]
Validator has been moved to spec repo, see discussion on the documentation format in 
https://github.com/bioimage-io/spec-bioimage-io/issues/91
