### ISSUE TITLE
Extend bioimageio command line interface?

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/python-bioimage-io#87]
Is it possible to extend the `bioimageio` commands with the command line functionality of this package?
See https://github.com/bioimage-io/spec-bioimage-io/blob/main/bioimageio/spec/__main__.py.

**Comment by FynnBe** [comment]
let's parse the spec ones through if injection doesn't work...

**Comment by constantinpape** [comment]
This is fixed now.
