### ISSUE TITLE
ensure_raw_resource_description vs load_raw_resource_description

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/python-bioimage-io#94]
.. only difference between the two is that 'ensure' also accepts resource description objects and (and this is the meaningful difference) returns a tuple of raw resource description (just as load.. does) and **root_path**

the separate handling of root_path in many places blows up the code slightly. it might be more elegant to allow setting a `root_path` member on resource description objects. 

pro:
- slimmer code base, e.g. `ensure_raw_resource_description` can be absorbed into load_raw_resource_description

contra:
 - `root_path` is not part of the spec, thus this is slightly monkey-patched

neutral:
- resource description as dicts do not have a `root_path`, the current handling then assumes the current working directory as `root_path`. This would not have to change.
  
  any thoughts, @constantinpape ?

**Comment by constantinpape** [comment]
Is there any case where the behavior of `load_raw_resource_description` is preferable over `ensure_...`? 
If not, could we just replace `load...` with `ensure...`? The only downside is that the returnvalue of `load_...` would change, but given that we don't have external users yet and need to change things anyway I think that that would be ok.

**Comment by FynnBe** [comment]
> Is there any case where the behavior of `load_raw_resource_description` is preferable over `ensure_...`?
> If not, could we just replace `load...` with `ensure...`? The only downside is that the returnvalue of `load_...` would change, but given that we don't have external users yet and need to change things anyway I think that that would be ok.

If we do that we might as well set a `root_path` attribute and conclude that once a resource is loaded the files on disk may not be moved (or write a helper function for that, but we currently have no use for it.). Setting root_path as attribute would avoid confusion about returning a tuple and hide it whereever root_path is not needed and shorten function signatures (most functions that accept a raw RD, also need root_path).

**Comment by constantinpape** [comment]
> If we do that we might as well set a `root_path` attribute and conclude that once a resource is loaded the files on disk may not be moved (or write a helper function for that, but we currently have no use for it.). Setting root_path as attribute would avoid confusion about returning a tuple and hide it whereever root_path is not needed and shorten function signatures (most functions that accept a raw RD, also need root_path).

I agree, that's a good solution as well. As long as you don't mind adding root_path although it's not a real part of the spec. (I don't think there is an issue with adding it.)

**Comment by constantinpape** [comment]
I think this is solved and we only have `load_raw_resource_description` + `root_path` is an attribute of the model now.
Is that correct, @FynnBe? Reopen if not.

**Comment by FynnBe** [comment]
this is not implemented yet...
