### ISSUE TITLE
setup different environments?

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/python-bioimage-io#96]
package conflicts for the joint pytorch tensorflow dev env...

maybe to cut this short we should setup different environments?

_Originally posted by @FynnBe in https://github.com/bioimage-io/python-bioimage-io/issues/95#issuecomment-916074944_

**Comment by constantinpape** [comment]
yep, I can look into this now.

**Comment by FynnBe** [comment]
implemented in #97
